### PR TITLE
Fix testing and algorithm 2 template

### PR DESCRIPTION
**Pull request by DendyA**
Work on this branch consists of testing suite bug fixes and also algorithm 2 template implementation work. This branch has development work that was merged from an old branch. Algorithm 2 should be fully implemented and tested with different edge cases and use cases.

### CODE REVIEW

**Comment by DendyA** [comment]
The test check is failing due to an issue with connecting to the database.

**Review by TyRicard — APPROVED** [review]
Looks good to me!

**Review by ethan-mcnamara — APPROVED** [review]
Failing pytest tests is acceptable as they will be refactoring after this pr is merged

**Comment by DendyA** [comment]
Passed review of a codeowner and a secondary team member. Overriding the requirement that all codeowners have to review.

**Pull request merged**
