### PR TITLE
Manipulate the incoming data to send to the algorithm.

### PR DESCRIPTION
**Pull request by DendyA**
Added logic into the endpoint that will extract the course name and code to pass to the algorithm once implemented. If the incoming capacity for a given course is 0, it will be predicted for. Otherwise, it will be ignored since it is assumed that the capacity was either already predicted or overridden by an admin user.

### CODE REVIEW

**Comment by DendyA** [comment]
Directly implements logic to satisfy issue #36.

**Comment by DendyA** [comment]
One note: the endpoint logic ASSUMES that the returned value from the algorithm will be the integer. The testing code of the algorithm currently returns a string. This will have to be changed before the final implementation.

**Comment by DendyA** [comment]
Added some quick error checking that was missing in the case where the linear regression function could not connect to the db correctly. Added a TODO in response to PR #47 . This code should be good to merge if it passes reviews. Once the algorithm code is finished and merged to main, then the code here will be revisited and un-commented as needed.

**Comment by DendyA** [comment]
Added some error handling in case the incoming data is malformed for any reason. Should be good for reviews now.

**Comment by DendyA** [comment]
Made a commit after some discussion about some changes. The code now returns an empty object if it received no data. In addition, a redundant indx was also removed.

**Review by TyRicard — APPROVED** [review]
This looks good to me

**Review by ethan-mcnamara — APPROVED** [review]

**Pull request merged**
